### ISSUE TITLE
Python version of code

### ISSUE THREAD

**Issue by ChidanandKumarKS** [vbrebion/rt_of_low_high_res_event_cameras#1]
Hi,

Thanks for outsourcing code. Very useful
Do you have python version of code? Thanks

**Comment by vbrebion** [comment]
Hi,

Thank you very much for your interest in our work!

Unfortunately, we do not have a Python version of the code available. One of our main goals was to propose a real-time compatible method, hence the choice of C++/CUDA.
In theory, a Python equivalent could be developed, but it would require quite some work and would probably be quite slow.

Let me know if you have any other question or remarks.

Best,
Vincent

**Comment by ChidanandKumarKS** [comment]
Thanks vincent for you kind reply. Closing the issue
